// Auto-generated by scripts/create-pools.ts — do not edit manually

// V3 contracts
export const V3_FACTORY_ADDRESS = "0x4752ba5DBc23f44D87826276BF6Fd6b1C372aD24" as `0x${string}`;
export const V3_SWAP_ROUTER_ADDRESS = "0x94cC0AaC535CCDB3C01d6787D6413C739ae12bc4" as `0x${string}`;
export const V3_POSITION_MANAGER_ADDRESS = "0x27F971cb582BF9E50F397e4d29a5C7A34f11faA2" as `0x${string}`;
export const V3_QUOTER_ADDRESS = "0xC5290058841028F1614F3A6F0F5816cAd0df5E27" as `0x${string}`;

// V4 contracts
export const V4_POOL_MANAGER_ADDRESS = "0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408" as `0x${string}`;
export const V4_POSITION_MANAGER_ADDRESS = "0x4b2c77d209d3405f41a037ec6c77f7f5b8e2ca80" as `0x${string}`;
export const PERMIT2_ADDRESS = "0x000000000022D473030F116dDEE9F6B43aC78BA3" as `0x${string}`;

export interface PoolConfig {
  version: "v3" | "v4";
  pair: string;
  token0: { address: `0x${string}`; symbol: string; decimals: number };
  token1: { address: `0x${string}`; symbol: string; decimals: number };
  fee: number;
  tickSpacing: number;
  hooks: `0x${string}`;
  poolAddress?: `0x${string}`;
}

export const V3_POOLS: PoolConfig[] = [
  {
    version: "v3",
    pair: "WETH/AAVE",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa99e1994f37397a1c174d20acc9147869460ece6" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xeA3F65546AFF7189be35270408eaA81E0277C340" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/WETH",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x495268bdca3Dc7D6B02B946C23d28ebc0242CabF" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/DAI",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x3A96113e13c66e6C63457c6A3E5A486FfC27822b" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/USDT",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xFA0c884EA4D5A6D420F544385aB33019231CcEb7" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/WBTC",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xc9C094b7bE032730C28B5CA52c19C5bb4fAE4d7D" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/LINK",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x57FF793bF738d88432Eb0D7D72Fa4caE7891C881" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/DAI",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x5C58fD91E739363a21048bF0c1635418A6DcfA3E" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x795BCCaf219f08403A2ec03121dD141FB4201A6D" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/LINK",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x0050758FBdA20ef175589Bd0F1929BD6E3922123" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/UNI",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "UNI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x14d29eE752D2dFd0252BD7293d74C94F136bB898" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/ARB",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xa61A1f52625039E7f4481F7d4eb4864FF7A57195" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/OP",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb687b48ed8b3a367ca23b4f365b3568e2a8da0d9" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x33349eE070861C13BbD01249AF5210B63754F057" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/MKR",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xe7e7fb85a33ce518c39df92ab6a7cebe55cd0b6c" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x6203fa5AE2f88b6386716912D0b597d72d90f787" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/DOGE",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0x7a7d8d490df543f093f296bb76beb56cdbb683cb" as `0x${string}`, symbol: "DOGE", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xaf61854971Ec7f76020f7E97a6729cF6269137F2" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/UNI",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "UNI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xEc5a6bf0D7f8422Bd804822E404E0Cff69F0619B" as `0x${string}`,
  },
];

export const V4_POOLS: PoolConfig[] = [
  {
    version: "v4",
    pair: "USDC/WETH",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/DAI",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 100,
    tickSpacing: 1,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/USDT",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 100,
    tickSpacing: 1,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/WBTC",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/LINK",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/AAVE",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa99e1994f37397a1c174d20acc9147869460ece6" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/ARB",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/OP",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb687b48ed8b3a367ca23b4f365b3568e2a8da0d9" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/DAI",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/USDT",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/LINK",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/AAVE",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa99e1994f37397a1c174d20acc9147869460ece6" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/ARB",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/OP",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb687b48ed8b3a367ca23b4f365b3568e2a8da0d9" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/COMP",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0x9c462dbd59ff0675b31970d11bb3ae93e7283681" as `0x${string}`, symbol: "COMP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/CRV",
    token0: { address: "0x12e2b23b99429c7738ec3dc4682ddc437a3a3fd5" as `0x${string}`, symbol: "CRV", decimals: 18 },
    token1: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/GRT",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xea79f42fddd4f60b8690df944aacd2545a34f086" as `0x${string}`, symbol: "GRT", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/LDO",
    token0: { address: "0x06d530d52c9949fb13c6a062e9b4941cbc25b60d" as `0x${string}`, symbol: "LDO", decimals: 18 },
    token1: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/PEPE",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb2b9ebf602ef3f737283697921ac25788bdcf56a" as `0x${string}`, symbol: "PEPE", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/SHIB",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0x8c645f07a0727a28774bc7afd1ea5e1cd8083a1f" as `0x${string}`, symbol: "SHIB", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/MATIC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0x8637576850b339d41cda9559dc6c10992dc7acc5" as `0x${string}`, symbol: "MATIC", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/DOGE",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0x7a7d8d490df543f093f296bb76beb56cdbb683cb" as `0x${string}`, symbol: "DOGE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/COMP",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0x9c462dbd59ff0675b31970d11bb3ae93e7283681" as `0x${string}`, symbol: "COMP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/PEPE",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb2b9ebf602ef3f737283697921ac25788bdcf56a" as `0x${string}`, symbol: "PEPE", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/UNI",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "UNI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/SNX",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0x89596c433ea951750c9e165d827f77e1b9c225f9" as `0x${string}`, symbol: "SNX", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/UNI",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "UNI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/MKR",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xe7e7fb85a33ce518c39df92ab6a7cebe55cd0b6c" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/MKR",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xe7e7fb85a33ce518c39df92ab6a7cebe55cd0b6c" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
];

export const ALL_POOLS: PoolConfig[] = [...V3_POOLS, ...V4_POOLS];

/** Look up pools by token symbol */
export function getPoolsForToken(symbol: string): PoolConfig[] {
  return ALL_POOLS.filter(
    (p) => p.token0.symbol === symbol || p.token1.symbol === symbol
  );
}

/** Get unique token list from all pools */
export function getPoolTokens(): Array<{ address: `0x${string}`; symbol: string; decimals: number }> {
  const seen = new Set<string>();
  const tokens: Array<{ address: `0x${string}`; symbol: string; decimals: number }> = [];
  for (const pool of ALL_POOLS) {
    for (const t of [pool.token0, pool.token1]) {
      if (!seen.has(t.address)) {
        seen.add(t.address);
        tokens.push(t);
      }
    }
  }
  return tokens;
}
