// Auto-generated by scripts/create-pools.ts — do not edit manually

// V3 contracts
export const V3_FACTORY_ADDRESS = "0x0227628f3F023bb0B980b67D528571c95c6DaC1c" as `0x${string}`;
export const V3_SWAP_ROUTER_ADDRESS = "0x3bFA4769FB09eefC5a80d6E87c3B9C650f7Ae48E" as `0x${string}`;
export const V3_POSITION_MANAGER_ADDRESS = "0x1238536071E1c677A632429e3655c799b22cDA52" as `0x${string}`;
export const V3_QUOTER_ADDRESS = "0xEd1f6473345F45b75F8179591dd5bA1888cf2FB3" as `0x${string}`;

// V4 contracts
export const V4_POOL_MANAGER_ADDRESS = "0xE03A1074c86CFeDd5C142C4F04F1a1536e203543" as `0x${string}`;
export const V4_POSITION_MANAGER_ADDRESS = "0x429ba70129df741B2Ca2a85BC3A2a3328e5c09b4" as `0x${string}`;
export const PERMIT2_ADDRESS = "0x000000000022D473030F116dDEE9F6B43aC78BA3" as `0x${string}`;

export interface PoolConfig {
  version: "v3" | "v4";
  pair: string;
  token0: { address: `0x${string}`; symbol: string; decimals: number };
  token1: { address: `0x${string}`; symbol: string; decimals: number };
  fee: number;
  tickSpacing: number;
  hooks: `0x${string}`;
  poolAddress?: `0x${string}`;
}

export const V3_POOLS: PoolConfig[] = [
  {
    version: "v3",
    pair: "USDC/WETH",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xA3d1b324ec3B2F78f55923790b2871241763cc9c" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/DAI",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xe918e5266d250c55fdb8ccf8e427bf23bb46b90f" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xFa637455A9Cb8b55B5aD7835305181fE60f26639" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/USDT",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x9b893c24c08d401355304Ebdf7EC2cE54D656D12" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xc993FFD1130D246D51343E74d062CC0F77777708" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/LINK",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xC382f8FDC631BF4707e40198b8D7cbE57A8b2aB4" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/DAI",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xe918e5266d250c55fdb8ccf8e427bf23bb46b90f" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x612D8794053838855e1895248Fd86E28b3a0E486" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xCb991e8b90e8F4b685bA7D064D1EEd0D1aa80ae6" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/LINK",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x545d092bc3970401Ff6Ff53c000FE2460dD8b26c" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/UNI",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "UNI", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x45119773A527c02Bb853319EA7E8B7aa75855CA5" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/AAVE",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x1889d9B34Fe1e62be24b65D14f523DCBf73db7DF" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/ARB",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xb96D462139129Fa2eAe69D120642df7f2f24b59D" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/OP",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xf3436F2D047519bF382a5EeEe66B409A5954cE27" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/MKR",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xDbf2cE3Ee6dFe714b642f07b244e41aBE2fc0aF7" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "WETH/DOGE",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb2b9ebf602ef3f737283697921ac25788bdcf56a" as `0x${string}`, symbol: "DOGE", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0xD687f0113F26b11D6D485C40E5bbA657ec29449E" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/UNI",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "UNI", decimals: 18 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
    poolAddress: "0x62A0aDe98e045F78d25267656f797142F6c470f4" as `0x${string}`,
  },
  {
    version: "v3",
    pair: "USDC/SHIB",
    token0: { address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xea79f42fddd4f60b8690df944aacd2545a34f086" as `0x${string}`, symbol: "SHIB", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
];

export const V4_POOLS: PoolConfig[] = [
  {
    version: "v4",
    pair: "USDC/WETH",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/DAI",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xe918e5266d250c55fdb8ccf8e427bf23bb46b90f" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 100,
    tickSpacing: 1,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/USDT",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 100,
    tickSpacing: 1,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/LINK",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/UNI",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "UNI", decimals: 18 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/AAVE",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/ARB",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/OP",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/SNX",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xa99e1994f37397a1c174d20acc9147869460ece6" as `0x${string}`, symbol: "SNX", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/DAI",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xe918e5266d250c55fdb8ccf8e427bf23bb46b90f" as `0x${string}`, symbol: "DAI", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/USDT",
    token0: { address: "0x01628afa8fe8f78d8aef0a22e2d7efc23483d5b9" as `0x${string}`, symbol: "USDT", decimals: 6 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/WBTC",
    token0: { address: "0x2d3f715022a81c39b102fafe5d3d119561e6e38f" as `0x${string}`, symbol: "WBTC", decimals: 8 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/LINK",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xf019feed5b9c23927e562db1b81a38c553041b87" as `0x${string}`, symbol: "LINK", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/UNI",
    token0: { address: "0x008607499b9c7dff6c539ff9629450cc5ce8d0a0" as `0x${string}`, symbol: "UNI", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/AAVE",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xa1f7e52301dc0201ff935e133ea7cddcee388b38" as `0x${string}`, symbol: "AAVE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/ARB",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xc7c55a318c5c05dc5060dc28d01e8237b5057951" as `0x${string}`, symbol: "ARB", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/OP",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb90ace2f72be1f5a916c0b9937b70a9ee2849463" as `0x${string}`, symbol: "OP", decimals: 18 },
    fee: 500,
    tickSpacing: 10,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/MKR",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/COMP",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb687b48ed8b3a367ca23b4f365b3568e2a8da0d9" as `0x${string}`, symbol: "COMP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/CRV",
    token0: { address: "0x89596c433ea951750c9e165d827f77e1b9c225f9" as `0x${string}`, symbol: "CRV", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/GRT",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xe7e7fb85a33ce518c39df92ab6a7cebe55cd0b6c" as `0x${string}`, symbol: "GRT", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/LDO",
    token0: { address: "0x9c462dbd59ff0675b31970d11bb3ae93e7283681" as `0x${string}`, symbol: "LDO", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/PEPE",
    token0: { address: "0x12e2b23b99429c7738ec3dc4682ddc437a3a3fd5" as `0x${string}`, symbol: "PEPE", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/SHIB",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xea79f42fddd4f60b8690df944aacd2545a34f086" as `0x${string}`, symbol: "SHIB", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/MATIC",
    token0: { address: "0x06d530d52c9949fb13c6a062e9b4941cbc25b60d" as `0x${string}`, symbol: "MATIC", decimals: 18 },
    token1: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "WETH/DOGE",
    token0: { address: "0xa1811a3d805b4e71e6787936480cb226681da5ae" as `0x${string}`, symbol: "WETH", decimals: 18 },
    token1: { address: "0xb2b9ebf602ef3f737283697921ac25788bdcf56a" as `0x${string}`, symbol: "DOGE", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/MKR",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb0a82cfe03ec1a6b9c6b821cefc56b6ea8dc73fa" as `0x${string}`, symbol: "MKR", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/COMP",
    token0: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xb687b48ed8b3a367ca23b4f365b3568e2a8da0d9" as `0x${string}`, symbol: "COMP", decimals: 18 },
    fee: 3000,
    tickSpacing: 60,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/PEPE",
    token0: { address: "0x12e2b23b99429c7738ec3dc4682ddc437a3a3fd5" as `0x${string}`, symbol: "PEPE", decimals: 18 },
    token1: { address: "0x46ea40b1190ef2c06e7660b0fa07f28a76658336" as `0x${string}`, symbol: "USDC", decimals: 6 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
  {
    version: "v4",
    pair: "USDC/SHIB",
    token0: { address: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" as `0x${string}`, symbol: "USDC", decimals: 6 },
    token1: { address: "0xea79f42fddd4f60b8690df944aacd2545a34f086" as `0x${string}`, symbol: "SHIB", decimals: 18 },
    fee: 10000,
    tickSpacing: 200,
    hooks: "0x0000000000000000000000000000000000000000" as `0x${string}`,
  },
];

export const ALL_POOLS: PoolConfig[] = [...V3_POOLS, ...V4_POOLS];

/** Look up pools by token symbol */
export function getPoolsForToken(symbol: string): PoolConfig[] {
  return ALL_POOLS.filter(
    (p) => p.token0.symbol === symbol || p.token1.symbol === symbol
  );
}

/** Get unique token list from all pools */
export function getPoolTokens(): Array<{ address: `0x${string}`; symbol: string; decimals: number }> {
  const seen = new Set<string>();
  const tokens: Array<{ address: `0x${string}`; symbol: string; decimals: number }> = [];
  for (const pool of ALL_POOLS) {
    for (const t of [pool.token0, pool.token1]) {
      if (!seen.has(t.address)) {
        seen.add(t.address);
        tokens.push(t);
      }
    }
  }
  return tokens;
}
